version: '3.8'

services:
  frontend:
    image: venkynagidi/frontend:one
    ports:
      - "8080:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
 
  
  
